### ISSUE TITLE
Feature request: read byte values, print byte value

### ISSUE THREAD

**Issue by redfast00** [LucasMW/Headache#2]
Right now, the read command can only read numbers. It would be cool if there were a command for reading a character from stdin and directly putting that value in a byte.

**Comment by LucasMW** [comment]
I thought about that, and the best solution seems to be adding a `char type`
That way you could do something like
```
char c;
read c;
print c;
```
and hac would assign these with simple commas and dots in instead of assign the brainfuck algorithms for reading and printing bytes.
Casting should solve handling chars and bytes together;
Code such as 
```
byte b; char c;
b = c as byte;
c = b as char;
```

However, implementing this naively right now might cause conflicts with how hac handles strings and bitwidth expansions.

**Comment by LucasMW** [comment]
@redfast00 commit a8388c3557809ba010966576e73c832b77ab0270
should solve it.
Tell me if there are any problems with that.
