### ISSUE TITLE
Optimize brainfuck code

### ISSUE THREAD

**Issue by none-None1** [LucasMW/Headache#4]
I compiled this headache program:
```text
void main(){
    int a;
    int b;
    #a;
    #b;
    @((a+b) as int);
}
```
and found out that the size of the resulting program can be easily optimized by removing redundant `+-`'s and `<>`'s and `-+`'s and `><`'s.

Also, there is the page [brainfuck constants](https://esolangs.org/wiki/Brainfuck_constants), so I think you can perhaps optimize the Hello World examples?

**Comment by LucasMW** [comment]
Hello. 

Yes, source to source optimization eliminating redundant character pairs is yet to be implemented, but it could be done easily.
Implementing brainfuck constants is more complicated however, because the methods on brainfuck constants use several cells and current implementation uses just one per constant.

For optimizing your program, consider using **byte** in instead of int. Or even **short** in instead of int. Int is quite slow and demands a lot of instructions.

Consider doing

```
void main(){
    byte a;
    byte b;
    #a;
    #b;
    @(a+b);
}
```

Or use shorts if you need larger numbers.

You can also pass -O1 to the compiler so it does constant folding optimization

**Comment by none-None1** [comment]
OK, now I know
